name: CI Build

on:
  push:
    branches: [ master, main ]
    paths:
      - 'CRIF-Encrypt/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'CRIF-Encrypt/**'
      - '.github/workflows/**'

env:
  DOTNET_VERSION: '6.0.x'
  PROJECT_PATH: 'CRIF-Encrypt/CRIF-Encrypt.csproj'
  BUILD_CONFIGURATION: 'Release'

jobs:
  ci-build:
    name: Continuous Integration Build
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build application
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Run tests (if any)
      run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal
      continue-on-error: true

    - name: Publish quick build for validation
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} `
          --configuration ${{ env.BUILD_CONFIGURATION }} `
          --runtime win-x64 `
          --output ./build-validation `
          --no-self-contained

    - name: Validate executable
      shell: pwsh
      run: |
        $exePath = "./build-validation/CRIF-Encrypt.exe"
        if (Test-Path $exePath) {
          Write-Host "✅ Executable created successfully: $exePath"
          $fileInfo = Get-Item $exePath
          Write-Host "📁 File size: $([math]::Round($fileInfo.Length / 1MB, 2)) MB"
          Write-Host "📅 Created: $($fileInfo.CreationTime)"
        } else {
          Write-Error "❌ Executable not found!"
          exit 1
        }

    - name: Upload build artifact (CI)
      uses: actions/upload-artifact@v4
      with:
        name: ci-build-${{ github.sha }}
        path: ./build-validation/
        retention-days: 3
